# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b3eeceb2781cda50a1b13cd24dec20214cd9a2f27a7fdfd5d77bc2326cd9dbe959197a2ba93e281196274b8c099c18e54291ef8f12ba44af7df2ef8fc65cd2

test:
  secret_key_base: 68fcd39b6f998d9253d4a1e7b9b984e612d65fccbf8a475d02f951c04dec768b64fbc2b22d6132c8e8696788f1319d7162a810c7a634c0289444eb4c00fca9ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
